/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GatewayHandoffValueBgpPrioritySetup struct {
	AutoAs GatewayHandoffValueBgpPrioritySetupAutoAs `json:"autoAs,omitempty"`
	AutoMed GatewayHandoffValueBgpPrioritySetupAutoMed `json:"autoMed,omitempty"`
	CommunityMapping GatewayHandoffValueBgpPrioritySetupCommunityMapping `json:"communityMapping,omitempty"`
}
