/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DeviceSettingsLan struct {
	Interfaces []DeviceSettingsLanInterface `json:"interfaces,omitempty"`
	Management *Subnet                      `json:"management,omitempty"`
	Networks   []DeviceSettingsLanNetwork   `json:"networks,omitempty"`
	Visibility DeviceSettingsLanVisibility  `json:"visibility,omitempty"`
}
